#!/bin/bash


echo "
welcome to

█░░ █▀▀ █▀▀ ▀▀█▀▀ █▀▀█ █▀▀█ ░░▀ █▀▀ 
█░░ █▀▀ █░░ ░░█░░ █░░█ █▄▄▀ ░░█ ▀▀█ 
▀▀▀ ▀▀▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ █▄█ ▀▀▀
            |   _| 
   _ \   _\` |   _| 
  .__/ \__,_| _|   
 _|                

		publisher
"

source "./.lector_env/bin/activate"
pip install -r .requirements.txt

python .release.py


echo "
Goodbye.

We'll meet again.
"
