#!/bin/bash

echo "
welcome to

█░░ █▀▀ █▀▀ ▀▀█▀▀ █▀▀█ █▀▀█ ░░▀ █▀▀ 
█░░ █▀▀ █░░ ░░█░░ █░░█ █▄▄▀ ░░█ ▀▀█ 
▀▀▀ ▀▀▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ █▄█ ▀▀▀

            |   _| 
   _ \   _\` |   _| 
  .__/ \__,_| _|   
 _|                



Setting up..
"
source "./.lector_env/bin/activate"
pip install -r .requirements.txt
yarn dev

echo "




Goodbye.

We'll meet again.
"
