#!/usr/local/bin/python3
import subprocess
import os
import sys
from rich import print

package_manager = os.environ.get('LECTORJSPKG') or "yarn"

if len(sys.argv) > 1:
    package_manager = sys.argv[1]


print(f"\n\n[bold cyan] Bundling with package manager: {package_manager} [/bold cyan] \n\n")
subprocess.call("python sass", shell=True)
subprocess.call(f"{package_manager} run build", shell=True)

